# Generated by Django 5.2.11 on 2026-02-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='min_participants',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='stage_type',
            field=models.CharField(choices=[('ON', 'On Stage'), ('OFF', 'Off Stage')], default='OFF', max_length=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='participation_mode',
            field=models.CharField(choices=[('SOLO', 'Solo'), ('GROUP', 'Group')], default='SOLO', max_length=5),
        ),
    ]
