# Generated by Django 5.2.11 on 2026-02-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_description_alter_event_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prefix',
            field=models.CharField(default='NILL', max_length=5, unique=True),
        ),
    ]
