# Generated by Django 5.2.11 on 2026-02-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
