# Generated by Django 5.2.11 on 2026-02-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='house',
            field=models.CharField(choices=[('amritamayi', 'AMRITAMAYI'), ('anandamayi', 'ANANDAMAYI'), ('chinmayi', 'CHINMAYI'), ('jyothirmayi', 'JYOTHIRMAYI')], default='Undefined', max_length=200),
        ),
    ]
