# Generated by Django 5.2.11 on 2026-02-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('registration', 'Registration'), ('admin', 'Admin'), ('judge', 'Judge'), ('certification', 'Certification'), ('student', 'Student')], default='Student', max_length=20),
        ),
    ]
