# Generated by Django 5.2.11 on 2026-02-07 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChestNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_chess_number', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_time', models.DateTimeField(auto_now_add=True)),
                ('chest_number', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(choices=[('solo', 'Solo'), ('group', 'Group'), ('lit', 'lit')], default='solo', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_registrations', to='events.event')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'registered_by'), name='unique_user_event_registration')],
            },
        ),
    ]
