# Generated by Django 5.2.11 on 2026-02-12 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_prefix'),
        ('registrations', '0003_eventregistration_groupparticipants_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='chest_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'chest_number'), name='unique_event_chest_number'),
        ),
    ]
