# Generated by Django 5.2.11 on 2026-02-12 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_alter_eventregistration_chest_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='groupparticipants',
            constraint=models.UniqueConstraint(fields=('registration', 'user'), name='unique_user_in_registration'),
        ),
    ]
